// <auto-generated />
using System;
using Magic_Villa_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaVillaAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20221230164821_AddingVillaNumber")]
    partial class AddingVillaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magic_Villa_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Testing amenity here!",
                            CreatedDate = new DateTime(2022, 12, 30, 11, 48, 21, 166, DateTimeKind.Local).AddTicks(4490),
                            Details = "Testing Details here for you!",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa3.jpg",
                            Name = "Test Valla 1",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 1200,
                            UpdatedDate = new DateTime(2022, 12, 30, 11, 48, 21, 166, DateTimeKind.Local).AddTicks(4534)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Testing amenity here!",
                            CreatedDate = new DateTime(2022, 12, 30, 11, 48, 21, 166, DateTimeKind.Local).AddTicks(4537),
                            Details = "Testing Details here for you!",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa4.jpg",
                            Name = "Test Valla 2",
                            Occupancy = 3,
                            Rate = 150.0,
                            Sqft = 1000,
                            UpdatedDate = new DateTime(2022, 12, 30, 11, 48, 21, 166, DateTimeKind.Local).AddTicks(4538)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Testing amenity here!",
                            CreatedDate = new DateTime(2022, 12, 30, 11, 48, 21, 166, DateTimeKind.Local).AddTicks(4539),
                            Details = "Testing Details here for you!",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa5.jpg",
                            Name = "Test Valla 3",
                            Occupancy = 6,
                            Rate = 250.0,
                            Sqft = 1500,
                            UpdatedDate = new DateTime(2022, 12, 30, 11, 48, 21, 166, DateTimeKind.Local).AddTicks(4540)
                        });
                });

            modelBuilder.Entity("Magic_Villa_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Number");

                    b.ToTable("VillaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
